### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by meredithcat** [imthaghost/eStore#2]
CRUD + Resource Association: 4
Documentation: 4
Test Coverage: 2
Templates: 4
Heroku: 3
Git Commits: 4

Comments:
- Great project delivery - it is clear that you put in a lot of effort for this project. I hope you learned a lot from it and will take those skills with you into your future classes and personal projects! 
- There is a small bug with the shopping cart link - the "Cart" link (when already on the cart page) goes to a Not Found. Looks like it is just a broken link.
- Ideally I would like to see more testing than just checking status code - e.g. on a 'POST', is the correct data being sent to the db?

**Comment by imthaghost** [comment]
Fixed the shopping cart button, i'll also add more test coverage :) Thanks for the feedback!
